### ISSUE TITLE
Resizing the dialog after creation

### ISSUE THREAD

**Issue by igvk** [kpreisser/TaskDialog#3]
Is it possible to resize the dialog after creation?
For example, I would like to change the width of it on expanded event.

**Comment by kpreisser** [comment]
Hi,
unfortunately the task dialog API doesn't provide a way to resize the dialog. You could try to manually do it using Windows APIs like [`SetWindowPos`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos) (and after that, re-set e.g. the the instruction with `page.Instruction = page.Instruction;` so that the dialog will update its layout for the new width).

Thanks!
